### ISSUE TITLE
Session support has been changed in Symfony 4.x

### ISSUE THREAD

**Issue by smalot** [php-earth/swoole-engine#4]
Services like `session.storage` are now private and can't be directly called is not passed by injection.

**Comment by petk** [comment]
Thanks for suggestion. Yes, I'm aware of all the changes in SF4... This might be added one day, but so far this project hit a dead end as a maintenance is concerned and won't be moving forward in this form anymore. Maybe something better will be done in the future elsewhere. Thanks for reporting and cheers.
