### ISSUE TITLE
Why is this not maintained anymore?

### ISSUE THREAD

**Issue by hariszukanovic** [php-earth/swoole-engine#5]
Did it have the expected (performance) result when used with Symfony?

**Comment by petk** [comment]
Hello, @hariszukanovic 

mostly due to lack of time and zero maintainers :)...

Symfony using Swoole extension has abnormaly huge performance otherwise.

We might bring this back somehow more in a form of a bundle than ubiquitous library/package...

**Comment by hariszukanovic** [comment]
Thanx for your answer...
Does this integration differ (much) from the "HttpKernel support" done in PHP-PM
https://github.com/php-pm/php-pm-httpkernel
?

**Comment by petk** [comment]
Yes, a very similar approach to the php-pm one... But of course adjusted specially for some headers things, and the $_SERVER filling etc. Also, the PHP-PM one is a bit more advanced in terms of handling watching for file changes, and some Twig optimizations. Once that would be added to Swoole integration also (from PHP side), that would boost performance to a level of factor 2x to 3x and even more.

Now, the most difficult thing here is exactly this syncing of the Swoole changes and Symfony's changes in the HttpKernel. Symfony also made quite a few steps forward already with better support for running such single bootstrapped apps. It's not a new thing actually and is on the goal even for the PHP core itself (hopefully for PHP 8).

**Comment by hariszukanovic** [comment]
While PHP 8.0 is too far away to wait for... I understand that the best bet would be to use PHP-PM to see how it affects our application..
Thanx!

**Comment by petk** [comment]
Sounds good... I think you'll love the performance with php-pm also quite alot. A bit less than PHP extension which is logical (PHP vs. C) but after all these are very extreme cases already.  If there's anything more to clear just ask. Closing this one since it looks resolved. Thanks.
